### ISSUE TITLE
List reporter not working as advertised

### ISSUE THREAD

**Issue by rdeforest** [bevry/kava#160]
Looks like whatever constructs the path to alternative reporters is incorrectly including 'console':

```console
$ KAVA_REPORTER=console node -e '(require("kava")).test("must pass", () => true)'
must pass
must pass ✔

1/1 tests ran successfully, everything passed

$ KAVA_REPORTER=list node -e '(require("kava")).test("must pass", () => true)'
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './reporters/console/list.js'
Require stack:
- /home/robert/node_modules/kava/source/index.js
- /home/robert/kava-bug-demo/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.addReporter (/home/robert/node_modules/kava/source/index.js:708:17)
    at Object.getReporters (/home/robert/node_modules/kava/source/index.js:581:12)
    at Object.report (/home/robert/node_modules/kava/source/index.js:741:29)
    at Object.exit (/home/robert/node_modules/kava/source/index.js:784:8)
    at process.<anonymous> (/home/robert/node_modules/kava/source/index.js:856:10)
    at process.emit (node:events:406:35) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/robert/node_modules/kava/source/index.js',
    '/home/robert/kava-bug-demo/[eval]'
  ]
}
```

**Comment by rdeforest** [comment]
Just discovered I can specify a correct path:

```console
$ KAVA_REPORTER=./reporters/list node -e '(require("kava")).test("must pass", () => true)'
✔ must pass

1/1 tests ran successfully, everything passed
```

**Comment by balupton** [comment]
https://github.com/bevry/kava/blob/5435e5facd0bf6874440f5495b63e029c56a6213/source/index.js#L701

**Comment by rdeforest** [comment]
I'm surprised the list of known reporters isn't derived from the contents of the reporters directory [(JavaScript here)](http://coffeescript.org/#try:%23%20untested%2C%20of%20course%0A%0A%7B%20openDir%2C%20readDir%2C%20stat%20%7D%20%3D%20require%20'fs%2Fpromises'%0A%7B%20resolve%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%3D%20require%20'path'%0A%0AdirEnts%20%3D%20(dir)%20-%3E%20readdir%20dir%2C%20withFileTypes%3A%20yes%0A%0AisModule%20%3D%20(path%2C%20dirent)%20-%3E%0A%20%20modIndexPath%20%3D%20resolve%20path%2C%20dirent.name%2C%20'index.js'%0A%0A%20%20if%20dirent.isDirectory()%20and%20(await%20stat%20modIndexPath).isFile()%0A%20%20%20%20modIndexPath%0A%0AmodulesInDirectory%20%3D%20(path)%20-%3E%0A%20%20modules%20%3D%20%5B%5D%0A%0A%20%20dir%20%3D%20await%20opendir%20path%0A%0A%20%20Object.assign%20%7B%7D%2C%20(%0A%20%20%20%20for%20await%20dirent%20from%20dirEnts%20dir%20when%20modPath%20%3D%20await%20isModule%20path%2C%20dirent%0A%20%20%20%20%20%20%5Bdirent.name%5D%3A%20modPath%0A%20%20)...):

```coffee
# untested, of course

{ openDir, readDir, stat } = require 'fs/promises'
{ resolve                } = require 'path'

dirEnts = (dir) -> readdir dir, withFileTypes: yes

isModule = (path, dirent) ->
  modIndexPath = resolve path, dirent.name, 'index.js'

  if dirent.isDirectory() and (await stat modIndexPath).isFile()
    modIndexPath

modulesInDirectory = (path) ->
  modules = []

  dir = await opendir path

  Object.assign {}, (
    for await dirent from dirEnts dir when modPath = await isModule path, dirent
      ['kava-reporter-' + dirent.name]: modPath
  )...
```

You could then replace the switch statement in addReporter with this:

```coffee
knownReporters = modulesInDirectory './reporters/'
path = knownReporters[                   reporter] ?
       knownReporters["kava-reporter-" + reporter] ?
                                         reporter
```

That way any reporters you put in that directory are automatically available via either their short name or their kava-reporter- name without having to update the code every time you add or remove a reporter.

**Comment by balupton** [comment]
@rdeforest kava can run in the browser too, no directories there
